# Generated by Django 6.0.1 on 2026-01-08 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudySessions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('subject', models.CharField(choices=[('Python', 'Python'), ('Django', 'Django'), ('REST API', 'REST API'), ('MySQL', 'MySQL'), ('MongoDB', 'MongoDB'), ('JavaScript', 'JavaScript'), ('NumPy', 'NumPy'), ('Pandas', 'Pandas'), ('Matplotlib', 'Matplotlib'), ('React', 'React'), ('HTML', 'HTML'), ('CSS', 'CSS'), ('Bootstrap', 'Bootstrap')], max_length=20)),
                ('planned_topic', models.CharField(max_length=200)),
                ('covered_topic', models.CharField(blank=True, max_length=200)),
                ('completed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
